name: Test Doltgres ORM integrations
on: [pull_request]

concurrency:
  group: ci-postgres-client-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  orm_integrations_job:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Build Docker image
        run: docker build -t doltgres-orm-tests -f testing/DoltgresORMDockerfile .
      - name: Run tests
        run: docker run --detach=false doltgres-orm-tests
